# run: conda env create --file environment.yml

name: pystempel-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pywin32
  - Cython
  - sortedcontainers
  - pytest
  - pyjnius
  - smart_open
  - tqdm
  - jupyterlab
  - pandas
  - matplotlib
