# run: conda env create --file environment.yml

name: pystempel-env
channels:
  - conda-forge
dependencies:
  - python=3.5
  - pip
  - pip:
    - sortedcontainers
    - pytest
    - Cython
    - pyjnius
    - smart_open
    - tqdm
