name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: "ubuntu-20.04"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
      - run: |
          conda info
          conda list